### ISSUE TITLE
color argument ignored for split2D

### ISSUE THREAD

**Issue by benneti** [JuliaDiffEq/DimensionalPlotRecipes.jl#6]
Currently when running
```
using Plots
using DimensionalPlotRecipes

plot(1:10, (x->1+(1im*x)).(1:10), transformation=:split2D)
plot!(1:10, (x->2+(2im*x)).(1:10), transformation=:split2D, :c=[2,2])
```
plots everything in color "1".
As `:color` is an alias for `:seriescolor` this one should be used in the recipe such that when explicitly setting the color it is not ignored.
So this would be fixed via
`seriescolor --> reshape([!iseven(i) ? i÷2+1 : i÷2 for i in 1:2size(A,2)],1,2size(A,2))`
but then without setting the color of the second plot explicitly it would have the same color as the first one.

Therefore what do you think about the following:
not setting the color but setting the imaginary parts as non primary.
This too is not perfect because then it is not possible to give the dashed lines labels.
But maybe something like 
`    label --> reshape([!iseven(i) ? "y$(i÷2+1) (solid: Re, dashed: Im)" : "" for i in 1:2size(A,2)],1,2size(A,2))` 
would work.

**Comment by ChrisRackauckas** [comment]
I'm open for suggestions/PRs. I agree that it's not so great that you cannot change the color.

**Comment by ChrisRackauckas** [comment]
Thanks!
